### ISSUE TITLE
dear

### ISSUE THREAD

**Issue by zyl520** [JC-Orozco/BlocksIDE#22] opened 2017-09-11 09:50 UTC
How did you do Resizable Workspace?

**Comment by zyl520** [comment] 2017-09-11 09:51
How did you do Resizable Workspace? Hope to get your reply

**Comment by JC-Orozco** [comment] 2017-09-11 13:03
This project uses React components for the user interface. The actual React component that resizes the panels is https://www.npmjs.com/package/react-split-pane
I am closing this issue since this is not a bug report.

**Closed as completed by JC-Orozco** 2017-09-11 13:03 UTC
